src/Entity/Adresse.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\AdresseRepository;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AdresseRepository::class)]
class Adresse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['listing'])]
    private ?int $id;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $Lot;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $Ville;

    #[ORM\OneToOne(mappedBy: 'Adresse', cascade: ['persist', 'remove'])]
    private ?User $user = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLot(): ?string
    {
        return $this->Lot;
    }

    public function setLot(string $Lot): static
    {
        $this->Lot = $Lot;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): static
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        // set the owning side of the relation if necessary
        if ($user->getAdresse() !== $this) {
            $user->setAdresse($this);
        }

        $this->user = $user;

        return $this;
    }

}

src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ContactRepository;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['listing','creating'])]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups(['listing','creating'])]
    private ?int $Tel = null;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $mail;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $linkdin;

    #[ORM\ManyToOne(inversedBy: 'Contact', cascade: ['persist', 'remove'])]
    private ?User $user = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTel(): ?int
    {
        return $this->Tel;
    }

    public function setTel(int $Tel): static
    {
        $this->Tel = $Tel;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getLinkdin(): ?string
    {
        return $this->linkdin;
    }

    public function setLinkdin(string $linkdin): static
    {
        $this->linkdin = $linkdin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Symfony\Component\Uid\Ulid;
use Symfony\Component\Uid\Uuid;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\UuidV4;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    
    #[ORM\Id]
    #[ORM\Column(type:"uuid", unique:true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class:'doctrine.uuid_generator')]
    #[Groups(['listing'])]
    private ?Uuid $id;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[Groups(['listing','creating'])]
    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[Groups(['listing','creating'])]
    #[ORM\Column]
    private ?int $Age = null;

    #[Groups(['listing','creating'])]
    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Adresse $Adresse = null;

    #[Groups(['listing','creating'])]
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Contact::class, cascade: ['persist', 'remove'])]
    private Collection $Contact;

    #[Groups(['listing'])]
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Etudes::class, cascade: ['persist', 'remove'])]
    private Collection $Etudes;

    #[Groups(['listing'])]
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Experiences::class, cascade: ['persist', 'remove'])]
    private Collection $Experience;

    public function __construct()
    {
        $this->Contact = new ArrayCollection();
        $this->Etudes = new ArrayCollection();
        $this->Experience = new ArrayCollection();
    }


    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->Age;
    }

    public function setAge(int $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getAdresse(): ?Adresse
    {
        return $this->Adresse;
    }

    public function setAdresse(Adresse $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContact(): Collection
    {
        return $this->Contact;
    }

    public function addContact(Contact $contact): static
    {
        if (!$this->Contact->contains($contact)) {
            $this->Contact->add($contact);
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): static
    {
        if ($this->Contact->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Etudes>
     */
    public function getEtudes(): Collection
    {
        return $this->Etudes;
    }

    public function addEtude(Etudes $etude): static
    {
        if (!$this->Etudes->contains($etude)) {
            $this->Etudes->add($etude);
            $etude->setUser($this);
        }

        return $this;
    }

    public function removeEtude(Etudes $etude): static
    {
        if ($this->Etudes->removeElement($etude)) {
            // set the owning side to null (unless already changed)
            if ($etude->getUser() === $this) {
                $etude->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Experiences>
     */
    public function getExperience(): Collection
    {
        return $this->Experience;
    }

    public function addExperience(Experiences $experience): static
    {
        if (!$this->Experience->contains($experience)) {
            $this->Experience->add($experience);
            $experience->setUser($this);
        }

        return $this;
    }

    public function removeExperience(Experiences $experience): static
    {
        if ($this->Experience->removeElement($experience)) {
            // set the owning side to null (unless already changed)
            if ($experience->getUser() === $this) {
                $experience->setUser(null);
            }
        }

        return $this;
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% for type, messages in app.flashes %}
            {% for message in messages %}
                <div class="alert alert-{{ type }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endfor %}
        {% endblock %}
    </body>
</html>

templates/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="container mt-4">
    <h1>Édition de l'utilisateur</h1>
      {{ form_start(form) }}
      <div class="form-row">
        <div class="col-md-4 mb-3">
          {{ form_row(form.Nom) }}
        </div>
        <div class="col-md-4 mb-3">
          {{ form_row(form.Prenom) }}
        </div>
        <div class="col-md-4 mb-3">
          {{ form_row(form.Age) }}
        </div>
      </div>

      <h2>Adresse</h2>
      <div class="form-row">
        <div class="col-md-6 mb-3">
          {{ form_row(form.Adresse.Lot) }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form_row(form.Adresse.ville) }}
        </div>
      </div>

      <h2>Contact:</h2>
      <div class="Contact" data-prototype="{{ form_widget(form.Contact.vars.prototype)|e('html_attr') }}">
        {% for contactForm in form.Contact %}
          <div class="form-row">
            <div class="col-md-4 mb-3">
              {{ form_row(contactForm.Tel) }}
            </div>
            <div class="col-md-4 mb-3">
              {{ form_row(contactForm.mail) }}
            </div>
            <div class="col-md-4 mb-3">
              {{ form_row(contactForm.linkdin) }}
            </div>
            <button type="button" class="btn btn-danger btn-sm remove-item">Supprimer</button>
          </div>
        {% endfor %}
      </div>
      <button type="button" class="btn btn-primary mt-2 mb-3 add-item" data-collection-holder-class="Contact">Ajouter un contact</button>

      <h2>Etudes:</h2>
      <div class="Etudes" data-prototype="{{ form_widget(form.Etudes.vars.prototype)|e('html_attr') }}">
        {% for etudeForm in form.Etudes %}
          <div class="form-row">
            <div class="col-md-4 mb-3">
              {{ form_row(etudeForm.Diplomes) }}
            </div>
            <div class="col-md-4 mb-3">
              {{ form_row(etudeForm.Date) }}
            </div>
            <button type="button" class="btn btn-danger btn-sm remove-item">Supprimer</button>
          </div>
        {% endfor %}
      </div>
      <button type="button" class="btn btn-primary mt-2 mb-3 add-item" data-collection-holder-class="Etudes">Ajouter des études</button>

      <h2>Experiences:</h2>
      <div class="Experience" data-prototype="{{ form_widget(form.Experience.vars.prototype)|e('html_attr') }}">
        {% for Experience in form.Experience %}
          <div class="form-row">
            <div class="col-md-4 mb-3">
              {{ form_row(Experience.DateDebut) }}
            </div>
            <div class="col-md-4 mb-3">
              {{ form_row(Experience.DateFin) }}
            </div>
            
            <div class="col-md-4 mb-3">
              {{ form_row(Experience.Titre) }}
            </div>
            <button type="button" class="btn btn-danger btn-sm remove-item">Supprimer</button>
          </div>
        {% endfor %}
      </div>
      <button type="button" class="btn btn-primary mt-2 mb-3 add-item" data-collection-holder-class="Etudes">Ajouter des Experiences</button>

      <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>
      {{ form_end(form) }}
  </div>
  

{% endblock %}

templates/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="container mt-4">
    <a href="{{ path('app_new') }}" class="btn btn-primary mb-3">Ajouter</a>
    <div class="row">
      {% for user in users %}
        <div class="col-md-6 mb-4">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">{{ user.Nom }} {{ user.Prenom }}</h3>
              <p class="card-text">Age: {{ user.age }}</p>

              <h2>Adresse:</h2>
              <p>{{ user.Adresse.lot }}</p>
              <p>{{ user.Adresse.ville }}</p>

              <h2>Contact</h2>
              <ul class="list-unstyled">
                {% for contact in user.Contact %}
                  <li>Tél: {{ contact.tel }}</li>
                  <li>Email: {{ contact.mail }}</li>
                  <li>LinkedIn: {{ contact.linkdin }}</li>
                {% endfor %}
              </ul>

              <h2>Etudes</h2>
              <ul class="list-unstyled">
                {% for Etudes in user.Etudes %}
                  <li>Diplômes: {{ Etudes.Diplomes }}</li>
                  <li>Date: {{ Etudes.Date|date('Y-m-d') }}</li>
                {% endfor %}
              </ul>

              <h2>Experience</h2>
              <ul class="list-unstyled">
                {% for Experience in user.Experience %}
                  <li>Date debut: {{ Experience.DateDebut|date('Y-m-d') }}</li>
                  <li>Date fin: {{ Experience.DateFin|date('Y-m-d') }}</li>
                  <li>Titre: {{ Experience.Titre}}</li>
                {% endfor %}
              </ul>

              <a href="{{ path('app_edit', {'id': user.id}) }}" class="btn btn-secondary">Edit</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col-md-4 mb-3">
                    {{ form_row(form.Nom) }}
                </div>
                <div class="col-md-4 mb-3">
                    {{ form_row(form.Prenom) }}
                </div>
                <div class="col-md-4 mb-3">
                    {{ form_row(form.Age) }}
                </div>
            </div>

            <h2>Adresse</h2>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    {{ form_row(form.Adresse.Lot) }}
                </div>
                <div class="col-md-6 mb-3">
                    {{ form_row(form.Adresse.ville) }}
                </div>
            </div>

            <h2>Contact:</h2>
            <div class="Contact" data-index="{{ form.Contact|length > 0 ? form.Contact|last.vars.name + 1 : 0 }}"
                data-prototype="{{ form_widget(form.Contact.vars.prototype)|e('html_attr') }}">
            </div>
            <button type="button" class="btn btn-primary mt-2 mb-3 add_item_link" data-collection-holder-class="Contact">Ajouter un contact</button>

            <h2>Etudes:</h2>
            <div class="Etudes" data-index="{{ form.Etudes|length > 0 ? form.Etudes|last.vars.name + 1 : 0 }}"
                data-prototype="{{ form_widget(form.Etudes.vars.prototype)|e('html_attr') }}">
            </div>
            <button type="button" class="btn btn-primary mt-2 mb-3 add_item_link" data-collection-holder-class="Etudes">Ajouter des études</button>

            <h2>Experience:</h2>
            <div class="Experience" data-index="{{ form.Experience|length > 0 ? form.Experience|last.vars.name + 1 : 0 }}"
                data-prototype="{{ form_widget(form.Experience.vars.prototype)|e('html_attr') }}">
            </div>
            <button type="button" class="btn btn-primary mt-2 mb-3 add_item_link" data-collection-holder-class="Experience">Ajouter des experiences</button>

            <div class="form-row">
                
            <button type="submit" class="btn btn-success">Envoyer</button>
            </div>
            {{ form_end(form) }}
    </div>

    <script>
        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);
            const item = document.createElement('div');
            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );
            collectionHolder.appendChild(item);
            collectionHolder.dataset.index++;
            addFormDeleteLink(item);
        };

        const addFormDeleteLink = (item) => {
            const removeFormButton = document.createElement('button');
            removeFormButton.innerText = 'Supprimer';
            removeFormButton.className = 'btn btn-danger mt-2';
            item.appendChild(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                item.remove();
            });
        };

        document.querySelectorAll('div.Contact div').forEach((contact) => {
            addFormDeleteLink(contact);
        });

        document.querySelectorAll('.add_item_link').forEach(btn => {
            btn.addEventListener("click", addFormToCollection);
        });
    </script>
{% endblock %}

templates/user.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}

    {{ form_row(form.Nom) }}
    {{ form_row(form.Prenom) }}
    {{ form_row(form.Age) }}

    <h2>Adresse</h2>
    {{ form_widget(form.Adresse) }}

    <h2>Contact:</h2>
    <ul class="Contact" data-index="{{ form.Contact|length > 0 ? form.Contact|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(form.Contact.vars.prototype)|e('html_attr') }}">
    </ul>
    <button type="button" class="add_item_link" data-collection-holder-class="Contact">Ajouter un contact</button>

    <h2>Etudes:</h2>
    <ul class="Etudes" data-index="{{ form.Etudes|length > 0 ? form.Etudes|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(form.Etudes.vars.prototype)|e('html_attr') }}">
    </ul>
    <button type="button" class="add_item_link" data-collection-holder-class="Etudes">Ajouter des études</button>

    <button type="submit">Envoyer</button>
    {{ form_end(form) }}

    <script>
        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);
            const item = document.createElement('li');
            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/g,
                    collectionHolder.dataset.index
                );
            collectionHolder.appendChild(item);
            collectionHolder.dataset.index++;
            addFormDeleteLink(item);
        };

        const addFormDeleteLink = (item) => {
            const removeFormButton = document.createElement('button');
            removeFormButton.innerText = 'Supprimer';
            item.append(removeFormButton);

            removeFormButton.addEventListener('click', (e) => {
                e.preventDefault();
                // remove the li for the tag form
                item.remove();
            });
        };

        document.querySelectorAll('ul.Contact li').forEach((contact) => {
            addFormDeleteLink(contact);
        });

        document.querySelectorAll('.add_item_link').forEach(btn => {
            btn.addEventListener("click", addFormToCollection);
        });
    </script>
{% endblock %}